#!/bin/bash
#===========#
#   MongoDB #
#===========#
export MONGODB_HOST=${MONGODB_HOST:-127.0.0.1}
export MONGODB_PORT=${MONGODB_PORT:-27017}
export MONGODB_DATABASE=${MONGODB_DATABASE:-yapi}
export MONGODB_USER=${MONGODB_USER:-yapi}
export MONGODB_PASSWORD=${MONGODB_PASSWORD:-pass4Yapi}
